bin/stacks/api-stack.ts, lib/entities/context/DutchQuoteContext.ts, test/unit/lib/entities/context/DutchQuoteContext.test.ts
Drops MM quote if it's at least 300% better than SOR price. Completes [this task](https://github.com/orgs/Uniswap/projects/22/views/28?pane=issue&itemId=34662635)
=> feat: drop rfq if price is too good comparing to SOR price

bin/stacks/api-stack.ts, lib/config/chains.ts, package.json, test/integ/quote-classic.test.ts, test/utils/tokens.ts, yarn.lock
Waiting on integ tests from routing-api then will add here
=> feat: add support for base

package.json, yarn.lock
to add new base deploy of UR for classic swaps
=> feat: bump universal router sdk

lib/entities/context/DutchQuoteContext.ts, lib/providers/quoters/RfqQuoter.ts, test/unit/lib/entities/context/DutchQuoteContext.test.ts, test/unit/lib/handlers/quote/handler.test.ts, test/utils/fixtures.ts
=> feat: changes for ETH output

lib/handlers/quote/handler.ts, lib/providers/quoters/RoutingApiQuoter.ts, lib/util/errors.ts, test/unit/lib/handlers/quote/handler.test.ts, test/unit/providers/quoters/RoutingApiQuoter.test.ts
- Surface 5xx from routing API
=> fix: surface routing api 5xx [WIP]

bin/stacks/api-stack.ts
This reverts commit f24020dcadf956016e959ef6a325ac2511200f77.
=> Revert "feat: try 512 memory (#240)"

lib/entities/context/DutchQuoteContext.ts, test/unit/lib/entities/context/DutchQuoteContext.test.ts
- Stop filtering out ETH out RFQ quotes
=> Fix filter out rfq quotes

bin/app.ts, test/integ/quote-classic.test.ts, test/integ/quote-gouda.test.ts
- skips flaky integ tests
- adds URA internal api key to integration test calls
=> fix: skip flaky tests and add internal api key to integ tests

package.json, yarn.lock
to pick up https://github.com/Uniswap/sdk-core/pull/83
=> bump sdk-core to v4.0.7

lib/entities/context/DutchQuoteContext.ts, lib/entities/context/index.ts, lib/providers/quoters/RoutingApiQuoter.ts, test/unit/lib/entities/context/QuoteContextHandler.test.ts
This reverts commit 7bd069c9785b6c47d4e495da55fcdde9ffaeba5b.
=> Revert "feat: add simulation flag for X comparisons (#261)"

bin/stacks/api-stack.ts
Updating our current ruleset to allow NYC Office connections and change priorities
=> feat: Updated IP based ACL

bin/app.ts, lib/constants.ts, lib/entities/quote/ClassicQuote.ts, lib/entities/quote/index.ts, lib/fetchers/PortionFetcher.ts, lib/fetchers/TokenFetcher.ts, lib/handlers/quote/injector.ts, lib/providers/index.ts, lib/providers/portion/PortionProvider.ts, lib/providers/portion/index.ts, lib/providers/quoters/RoutingApiQuoter.ts, lib/util/errors.ts, test/constants.ts, test/unit/lib/fetchers/PortionFetcher.test.ts, test/unit/providers/portion/PortionProvider.test.ts, test/unit/providers/quoters/RoutingApiQuoter.test.ts, test/utils/tokens.ts
[unified-routing-api](https://github.com/Uniswap/unified-routing-api) to integrate with portion service, for new data transfer object pattern.
=> feat: portion service integration

lib/entities/quote/ClassicQuote.ts, lib/entities/quote/DutchQuote.ts, lib/entities/quote/index.ts, lib/handlers/quote/handler.ts, lib/util/time.ts, test/unit/lib/handlers/quote/handler.test.ts
=> chore: add createdAtMs measurements

bin/app.ts, lib/constants.ts, lib/fetchers/PortionFetcher.ts, lib/handlers/quote/injector.ts, lib/util/portion.ts, test/integ/quote-classic.test.ts, test/integ/quote-gouda.test.ts, test/unit/lib/fetchers/PortionFetcher.test.ts
This PR broke fees, will investigte later as to why
=> Revert ForcePortion for testing

bin/app.ts, lib/constants.ts, lib/fetchers/PortionFetcher.ts, lib/handlers/quote/injector.ts, lib/util/portion.ts, test/integ/quote-classic.test.ts, test/integ/quote-gouda.test.ts, test/unit/lib/fetchers/PortionFetcher.test.ts
Unreverting ForcePortion logic
We discovered that this branch was not bugged, but rather the configuration in the secret was picked up again after we changed the env variable manually.
=> Unrevert ForcePortion

lib/entities/context/DutchQuoteContext.ts
Reverts Uniswap/unified-routing-api#318
https://uniswapteam.slack.com/archives/C064HPY2B5H/p1699401102694179
=> Revert "chore: remove route back to ETH calls"

package.json, yarn.lock
- This PR aims to upgrade the UR sdk dependency to `1.5.8` so it can be on par with the interface
=> feat: upgrade UR sdk to 1.5.8

.github/workflows/semgrep.yml
This adds a semgrep code scanning configuration
=> chore: Add semgrep configuration

.github/workflows/semgrep.yml
=> Chore: fixes path issue

package.json, test/unit/lib/fetchers/TokenFetcher.test.ts, yarn.lock
for some reason some new tokens being filtered
=> feat: bump tokenlist

test/constants.ts, test/integ/quote-classic.test.ts
disable mixed route test and increase DAI size
=> fix: integ tests

test/utils/forkAndFund.ts
the previous whale just lost some money
=> feat: add new agEUR whale

test/utils/forkAndFund.ts
the previous one was a contract that couldnt receive ETH
=> Add new ageur whale

test/integ/base.test.ts, test/integ/quote-classic.test.ts, test/integ/quote-gouda.test.ts
same fix as #366 but in many different places
=> fix(integ-test): force protocol selection in classic request everywhere

lib/constants.ts, lib/fetchers/PortionFetcher.ts, lib/handlers/quote/handler.ts, test/integ/quote-classic.test.ts, test/integ/quote-gouda.test.ts, test/unit/lib/fetchers/PortionFetcher.test.ts
We will pass the request source to the portion fetcher as it would be used to make decisions about the portion
=> feat(portion): Pass request source to portion fetcher

bin/app.ts, lib/entities/quote/DutchV2Quote.ts, test/unit/entities/DutchV2Quote.test.ts
fetch from secret and pass through env
=> feat: add RFQ cosigner address

bin/stacks/api-stack.ts
https://linear.app/uniswap/issue/CX-596/user-mentioning-they-may-be-blocked#comment-79dd6f7e
=> Increase 5 minute rate limiting api call rate

lib/handlers/quote/handler.ts, test/unit/lib/handlers/quote/handler.test.ts, test/utils/fixtures.ts, yarn.lock
- add v2 type
- yarn.lock
- Revert "yarn.lock"
=> fix: add v2 type check in getQuotedAMount

lib/entities/context/DutchQuoteContext.ts, lib/entities/context/DutchV2QuoteContext.ts, lib/entities/request/DutchRequest.ts, lib/entities/request/DutchV2Request.ts, lib/handlers/quote/injector.ts, lib/providers/quoters/RfqQuoter.ts, test/unit/lib/entities/context/DutchV2QuoteContext.test.ts, test/unit/lib/entities/quoteRequest.test.ts, test/unit/lib/handlers/quote/handler.test.ts, test/unit/providers/quoters/RfqQuoter.test.ts, test/utils/fixtures.ts, test/utils/quoteResponse.ts
- fix v2 request routing type
- protocolVer helper function
=> fix: explicit protocol version in rfq request

bin/app.ts, lib/entities/context/DutchQuoteContext.ts, lib/providers/quoters/RfqQuoter.ts
- fix rfqQuoter supported routingTypes
- fix pipeline
- remove unused value
- better names
=> fix: pipeline
