lib/entities/context/DutchQuoteContext.ts

This commit lowers the uniswapx gas threshold so we dont send orders
where gas makes up over 10% of the trade size

feat: lower uniswap gas threshold

---

lib/entities/request/ClassicRequest.ts
lib/providers/quoters/RoutingApiQuoter.ts

Quote Latencies have been high. We are exercising multiple paths to speed up the 1st quote. Ideas include:
1. Allow interface/mobile pass down the `debugRoutingConfig`, so that they can start experimenting/tuning with quote latencies without impacting prod traffics.
2. Routing backend keeps tuning and fixing the latencies bottlenecks in smart-order-router, and also leverage the `debugRoutingConfig` query string param without impacting prod traffics.
quote latencies are a factor of many dynamic things, and we want to live perf test in prod to have the most accurate perf datapoints.
We are passing down this `debugRoutingConfig`, a JSON-stringified alpha-router [configs](https://github.com/Uniswap/smart-order-router/blob/main/src/routers/alpha-router/alpha-router.ts#L264).
Tested in my local …

Feat: pass debug query string param to routing-api

---

lib/entities/request/ClassicRequest.ts
lib/providers/quoters/RoutingApiQuoter.ts
lib/util/validator.ts

quoteSpeed = fast sent to local unified-routing-api, and correctly forwarded to the local routing-api:
```
{
"amount":"1000000000000000000",
"protocols":"v2,v3,mixed",
"quoteSpeed":"fast",
"tokenInAddress":"ETH",
"tokenInChainId":"1",
"tokenOutAddress":"0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
"tokenOutChainId":"1",
"type":"exactIn"
},
"multiValueQueryStringParameters":{
"amount":[
"1000000000000000000"
],
"protocols":[
"v2,v3,mixed"
],
"quoteSpeed":[
"fast"
],
"tokenInAddress":[
"ETH"
],
"tokenInChainId":[
"1"
],
"tokenOutAddress":[
"0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
],
"tokenOutChainId":[
"1"
],
"type":[
"exactIn"
]
}
```

Feat: Support fast 1st quote at the unified-routing-api level

---

lib/constants.ts

Basically to account for the UX cost of wrapping weth

feat: increase WETH wrap overhead

---

bin/app.ts
lib/entities/context/ClassicQuoteContext.ts
lib/entities/context/DutchQuoteContext.ts
lib/entities/context/index.ts
lib/handlers/quote/handler.ts
lib/handlers/quote/injector.ts
lib/providers/index.ts
lib/providers/syntheticStatusProvider.ts
test/integ/quote-gouda.test.ts
test/unit/lib/entities/context/ClassicQuoteContext.test.ts
test/unit/lib/entities/context/DutchQuoteContext.test.ts
test/unit/lib/entities/context/QuoteContextHandler.test.ts
test/unit/lib/handlers/quote/handler.test.ts
test/unit/lib/handlers/quote/schema.test.ts

This commit adds a dynamic switch-on for synthetic UniswapX quotes using
the UPA enabled endpoint. It will automatically consider or reject
synthetic quotes depending on the response from this endpoint

feat: fetch synthetic status from UPA

---

lib/entities/request/ClassicRequest.ts
lib/providers/quoters/RoutingApiQuoter.ts
lib/util/validator.ts

Interface already fetches fee-on-transfer tax and shave off the quote amount. We need to protect smart-order-router fee-on-transfer tax [feature](https://github.com/Uniswap/smart-order-router/pull/395/files) under a feature flag, so that interface doesn't double FOT tax.
Routing-api corresponding PR https://github.com/Uniswap/routing-api/pull/361
Tested via:
```
curl 'https://ggy7t0yp57.execute-api.us-east-2.amazonaws.com/prod/quote' \
--data-raw '{
"tokenInChainId":1,
"tokenIn":"0x0D0A1767da735F725f41c4315E072c63Dbc6ab3D",
"tokenOutChainId":1,
"tokenOut":"0xab98093c7232e98a47d7270ce0c1c2106f61c73b",
"amount":"1000000000000000000",
"type":"EXACT_INPUT",
"configs":[
{
"protocols":[
"V2",
"V3",
"MIXED"
],
"routingType":"CLASSIC",
"unicornSecret":"MASKED",
"debugRoutingConfig": …
```

Expose enableFeeOnTransferFeeFetching post request field

---

lib/entities/context/DutchQuoteContext.ts
lib/entities/context/index.ts
lib/providers/quoters/RoutingApiQuoter.ts
test/unit/lib/entities/context/QuoteContextHandler.test.ts

This commit adds the simulateFromAddress flag to classic quotes when
used as a comparison device for UniswapX quotes. This should make the
gas adjustments more accurate giving us a better view when selecting
quote types for users

feat: add simulation flag for X comparisons

---

lib/entities/context/DutchQuoteContext.ts
lib/entities/context/index.ts
lib/entities/request/ClassicRequest.ts
lib/providers/quoters/RoutingApiQuoter.ts
test/unit/lib/entities/context/QuoteContextHandler.test.ts

- feat: add simulation flag for X comparisons (#261)
- fix: regenerate request instead of assigning

add gas simulations

---

lib/entities/quote/DutchQuote.ts
test/constants.ts

- Adds `orderHash` to the response of `/quote` for X quotes
- Allows integrators to later query their order if the do not get a response from when posting a new order
- The change is backwards compatible but we should make sure that we're not breaking the clients --> should not be an issue as they're also ignoring fields like the `encodedOrder`

feat: orderHash in `/quote` response

---

lib/providers/quoters/RoutingApiQuoter.ts
test/integ/quote-classic.test.ts

When generating the portionAmountDecimals response, if portionAmount is 0 we should default to returning 0 instead of undefined.

Set portionAmountDecimals to default 0 if undefined

---

lib/handlers/quote/injector.ts
lib/providers/syntheticStatusProvider.ts

Avoiding calls that always return false anyways

fix: remove synthetic status

---

lib/fetchers/TokenFetcher.ts
lib/handlers/quote/handler.ts
lib/handlers/quote/injector.ts
test/unit/entities/DutchQuote.test.ts
test/unit/lib/fetchers/TokenFetcher.test.ts
test/unit/lib/handlers/quote/handler.test.ts

We aren't filtering out dutch limit requests (RFQ quote requests) that have ineligible token addresses. We send the requests to the param service and then filter out the response if the token address for either token does not fall in the `DEFAULT_TOKEN_LIST`.
- Add a function `getTokenByAddress` to the `tokenFetcher` that will allow us to determine if token is in the default token list
- Add a function `isDutchEligible` to check all the pre-quote eligibility checks then remove dutch requests if necessary.
- Remove some leftover console.logs from fee team work
- Testing locally
- Unit tests

fix: remove dutch limit requests if ineligible

---

lib/fetchers/TokenFetcher.ts
lib/handlers/quote/handler.ts
test/unit/lib/handlers/quote/handler.test.ts

In my previous change #314, we weren't checking for the token symbol only the address. If a request was UniswapX but had token symbols for tokenIn/tokenOut the filter would remove the DUTCH_LIMIT requests.
- Change `getTokenByAddress` -> `getTokenByAddressOrSymbol`. First try fetching the token using symbol then if that fails use the address.
Curled locally
Unit tests fix
Ran integ test locally

fix: token filtering for UniswapX

---

lib/entities/context/DutchQuoteContext.ts
lib/entities/context/index.ts
lib/fetchers/Permit2Fetcher.ts
lib/handlers/quote/handler.ts

From https://github.com/Uniswap/routing-api/pull/404
> From this issue in ethers: https://github.com/ethers-io/ethers.js/issues/901
> We can switch to using the StaticJsonRpcProvider which avoids an unnecessary chainId call to infura, saving about 30% of requests to infura
The only issue is if we share a provider across different cross chain calls but we don't do that anywhere afaik. Also that wouldn't work since we don't have a multi chain rpc.

fix: Switch over to ethers StaticJsonProvider

---

lib/entities/context/DutchQuoteContext.ts

As part of our ongoing effort to reduce routing API / AWS costs we decided the lowest hanging fruit would be this extra routing api call. For every UniswapX call we are 2x calling routing api. This call checks if the output token for the UniswapX swap has a route back to ETH. The only reason we have this call is to ensure the broadcaster doesn't get stuck with an illiquid profit token. 
We want to do some costs cutting before rolling out X to 100% so part 1 of this initiative is to remove the call in URA and then part 2 would be to update the broadcaster to throw out illiquid swaps. This can be prioritized later as for right now it is most likely safe to assume back stopped order have a route back to ETH. Also, the broadcaster fills very small amount of orders.
Remove the route back to …

chore: remove route back to ETH calls

---

lib/constants.ts
lib/entities/context/DutchQuoteContext.ts
lib/entities/quote/DutchQuote.ts
lib/util/quoteMath.ts
package.json
test/unit/entities/DutchQuote.test.ts
test/unit/lib/entities/context/DutchQuoteContext.test.ts
test/unit/lib/util/quoteMath.test.ts
test/utils/fixtures.ts
yarn.lock

Use gas-related fields in classic quote to estimate trade size. Doing this for mainnet only because `gasUseEstimateUSD` isn't as reliable from what I've seen on L2s. 
e.g. ARB swap: `gasUseEstimateUSD": "3.641673351807764822"`

feat: override auctionPeriod to 120s for large (>= $10,000) trades on mainnet

---

lib/entities/request/index.ts
lib/handlers/quote/schema.ts
lib/providers/quoters/RoutingApiQuoter.ts

RoutingAPI receives an intent param that helps it change its configuration to adapt to different intents.
URA is just in charge of forwarding the param if it exists.

Forward intent param to RoutingAPI

---

test/integ/quote-gouda.test.ts
test/utils/forkAndFund.ts

Fix is to increase the trade size 10x. All the quoteUniswapX integ-test passed on my local https://app.warp.dev/block/bCIz89AkdhiKo8wpKcy5q6

Test-Fix: bullet whale insufficient ETH for gas & UniswapX USDC -> DAI quote

---

test/integ/quote-gouda.test.ts

RFQ quoter stopped returning quote for ETH -> USDC, and it blocks URA pipeline:
In order to unblock URA pipeline, we should fix the uniswapx portion integ-test to always use synthetic quote. It appears we cannot rely on RFQ quoter even for the most popular swap ETH -> USDC, even if the trade size is non-trivial (10 ETH).
quoteUniswapX integ-test after the test setup fix https://app.warp.dev/block/F7HTITuswHrunXlsyqUVJv

Test-Fix: portion uniswapx quote integ-test to always use synthetic quote for ETH -> USDC

---

lib/handlers/base/api-handler.ts
lib/handlers/quote/handler.ts

Removed two unnecessary logs. We log the entire request context and API Gateway event at the beginning of the request. This is one of our largest logs and the least useful. We also log the raw body of the request after we return a response. This is a duplicate log.

chore: removed uneccessary logs

---

jest.config.js
package.json
yarn.lock

Saw the backend team started using speedy web compiler and tested it out for URA. Works well!
ts-jest has a 6 - 12 second lag when compiling. This compilation lag gets extra bad if you run jest in watch mode. Instead, we can use [swc](https://swc.rs/docs/usage/jest#usage) as a drop-in replacement to reduce the lag to one second.

chore: speed up unit test compilation time.

---

bin/app.ts

- This PR aims to point URA to a new secret which includes a working version of a BNB RPC from QuickNode
- It also moves URA away from using X's RPCs
- The appropriate permissions have been given to the secret
- The secret has been been encrypted using CMK

feat: new RPCs secret with QuickNode for BNB RPC

---

test/utils/forkAndFund.ts

agEUR tests integ tests are failing because the previous whale addresses do not hold agEUR anymore.

fix: add layerzero ageur contract as whale addr

---

bin/app.ts
bin/stacks/api-stack.ts

Context: https://www.notion.so/uniswaplabs/AWS-Lambda-Best-Practices-781917c67edf4dcb96d22e38a6e46411
Adjust provisioned concurrency for both lambdas to adjust from 50 to 500. This reduces the minimum amount (from 150 to 50) but still allows for a lot of leeway. Also, increasing the sensitivy of the alarm so it can increase faster
Almost all invocations are serviced by provisioned concurrencies so this just allows for more flexibility.
Link: https://us-east-2.console.aws.amazon.com/lambda/home?region=us-east-2#/functions/prod-us-east-2-UnifiedRoutingAPI-QuoteE2906A56-51nVLFinECLL/aliases/live?tab=monitoring

feat: Adjust concurrencies for URA

---

lib/entities/quote/ClassicQuote.ts
lib/entities/quote/DutchQuote.ts
test/integ/quote-classic.test.ts
test/unit/entities/DutchQuote.test.ts
test/unit/lib/entities/context/DutchQuoteContext.test.ts
test/unit/lib/entities/quoteResponse.test.ts
test/unit/providers/quoters/RfqQuoter.test.ts
test/utils/fixtures.ts

- use portion object instead of raw fields inside quote objects
- smol helper to split a dutch output post fees, to be used to dedupe code b/t dutch order types

fix: small portion cleanup

---

.github/workflows/docs.yml

Minor change to pin the shaw hash for generating the docs

chore: pinning the gh action to a sha hash

---

package.json
yarn.lock

**NOTE**: DO NOT MERGE UNTIL THE URA and SOR v2 contracts changes make it to prod
- This PR aims to bump the UR sdk version to 1.7.1
- The big changes include the new router contracts (with v2 pools) and safeMode

chore: bump UR-sdk to 1.71

---

lib/entities/quote/DutchQuote.ts
lib/entities/quote/DutchV2Quote.ts
lib/util/validator.ts
test/constants.ts
test/unit/lib/entities/quoteRequest.test.ts
test/unit/lib/handlers/quote/schema.test.ts

and enforce every config has the proper routing type. Currently it would accept a dutch config with dutch_v2 routing type, a dutch config with classic routing type etc. Now each type is pegged to the routing type

feat: add dutch v2 routing tpe

---

bin/app.ts

We need to set a dummy env variable to force the beta secrets to reload

chore(deploy): Set env variable on beta lambda to reload secrets

---

bin/stacks/api-stack.ts
package.json
test/integ/quote-classic.test.ts
yarn.lock

If I don't pass in swapper in the classic quote request, I can get the quote back on blast: https://app.warp.dev/block/mENVV16CvXLSF8M6Pgascw. If I do pass in swapper, then I will get runtime error https://app.warp.dev/block/vkMMYMGTIV7DvCJH0fKZny. The reason is because by passing in swapper, URA will try to fetch [permit](https://github.com/Uniswap/unified-routing-api/blob/78f72f971601a5c2b53b34d3c50222e06c0b8cf2/lib/entities/context/ClassicQuoteContext.ts#L34) for the swapper. But ur-sdk 1.7.1 doesn't contain the [UNIVERSAL_ROUTER_ADDRESS](https://github.com/Uniswap/unified-routing-api/blob/78f72f971601a5c2b53b34d3c50222e06c0b8cf2/lib/entities/context/ClassicQuoteContext.ts#L39C9-L39C33) on blast yet. So the fix is to upgrade ur-sdk to 1.8.2 which contains the correct UR address on …

fix: bump ur-sdk to include UR deployed address on blast, and bump up lambda version to pick up the updated blast RPC URL from secret

---

test/integ/base.test.ts
test/integ/quote-xv2.test.ts

We've moved hard quote tests into GPA so we can remove it here

fix: remove xv2 integ tests for hard quote

---

test/integ/quote-xv2.test.ts

It's hard to debug when we don't throw on the caught error in the integ tests, instead we're getting "cannot read response of undefined"

fix: throw on non axios error

---

package.json
yarn.lock

There was a breaking change to the uniswapx-sdk which changed input and outputs in DutchV2 orders to baseInput and baseOutputs. We have decided to revert all changes back to `input` and `outputs` for the short term to fix downstream errors in other services until we determine a path forward.

fix: bump x sdk to latest alpha.10

---

lib/entities/request/ClassicRequest.ts
lib/entities/request/DutchRequest.ts
lib/entities/request/DutchV2Request.ts
lib/entities/request/RelayRequest.ts
lib/entities/request/index.ts
lib/handlers/quote/handler.ts
lib/providers/quoters/RoutingApiQuoter.ts
test/unit/providers/quoters/RoutingApiQuoter.test.ts

This PR adds a way to forward all headers coming from the URA to the RoutingAPI call. These headers will contain the x-request-source and x-app-version that we care about.

feat: Forward headers to RoutingAPI

---

lib/providers/quoters/RoutingApiQuoter.ts
test/unit/providers/quoters/RoutingApiQuoter.test.ts

AWS doesn't like to share headers, so we will manually pick the headers that we care about, in this case x-request-source and x-app-version

fix: Only forward request-source and app version headers

---

lib/entities/quote/DutchQuote.ts
lib/entities/request/DutchRequest.ts
lib/entities/request/RelayRequest.ts
lib/providers/quoters/RoutingApiQuoter.ts
test/unit/entities/DutchQuote.test.ts
test/unit/providers/quoters/RoutingApiQuoter.test.ts

when requesting dutch only, we build classic request and use its result
to parameterize our portion. however, we do not carry over all the
portion details. This commit updates it to simplify this process and
simply use the portion that already exists in the dutch quote if it is
there

fix: portion for synthetic dutch

---

lib/entities/context/DutchQuoteContext.ts
test/unit/lib/entities/context/DutchQuoteContext.test.ts
test/unit/providers/quoters/RoutingApiQuoter.test.ts
test/utils/fixtures.ts

- This PR aims to turn on the `enableUniversalRouter` option for the routing-api request needed to parameterize dutch only quotes
- Integration tests pass
- Still not sure how this was introduced

fix: turn on `enableUniversalRouter` for classic param of dutch quotes

---

lib/constants.ts
lib/entities/quote/RelayQuote.ts
test/unit/entities/RelayQuote.test.ts

Before we were incorrectly adding the gas adjustment to the fee start value instead of multiplying it by the ratio of the adjusted gas to the classic gas (like we do in Dutch quotes). This PR adds that logic and some comments. It also bumps the gas overhead to 130,000 which is closer to the estimated "worst case" gas overhead in relayed swaps.

fix: relay quote gas adjustments

---

lib/entities/quote/DutchQuote.ts
lib/entities/quote/DutchQuoteFactory.ts
lib/entities/request/DutchV1Request.ts
lib/entities/request/DutchV2Request.ts
test/unit/entities/DutchV2Quote.test.ts

This reverts commit 4e6e37fbaeb5842edb367c52ca4c3363f9587754.
This was an unintended merge that took place because of lack of guardrails that have now been turn on.
Specifically, the bypass setting on the `main` branch.

fix: undo `4e6e37fbaeb5842edb367c52ca4c3363f9587754` 

---

lib/util/validator.ts
test/unit/lib/handlers/quote/schema.test.ts

- This PR aims to modify a small validation that was accidentally introduce in the previous PR #419

fix: allow 0 `gasAdjustmentBps`

---

test/integ/base.test.ts
test/integ/quote-relay.test.ts

We decided to not execute quotes on chain in our integration tests due to general flakiness

fix: remove flaky relay execution tests

---

bin/stacks/api-stack.ts

I forgot to ask someone to add the ZORA JSON RPC URL into secret, before merging. Now I have to bump the lambda version so that the URA pipeline can pick up the new secret. I manually retried the entire URA beta stage, but still it can't find the secret:

chore: bump lambda version to pick up new Zora secret

---

lib/entities/context/DutchQuoteContext.ts
lib/fetchers/Permit2Fetcher.ts
lib/util/permit2.ts
test/unit/lib/fetchers/Permit2Fetcher.test.ts

Just realized that I haven't updated the permit2 address to make it distinctive on ZkSync.

fix: permit2 address different on zksync
